# test_deploy_app.py
# Run tests for webapp deployment
"""
role/webserver/tasks/deploy_app.yml
"""

import yaml
import pytest

ROLEPATH = "roles/webserver"
KEYPHRASE = [
    "Generated by Claude",
    "The History of Cats",
    "The goddess Bastet",
    "7500 BCE",
    "Cats in Ancient Egypt",
]
LOCAL_INDEX = f"{ROLEPATH}/files/data/index.html"

# Store vars into a workable dict
with open("vars/nginx.yml", "r") as fd:
    VARS = yaml.load(fd, yaml.SafeLoader)

# read entire file
with open(LOCAL_INDEX, "r") as fd:
    STATIC_PAGE = fd.read()


def test_deploy_static_page__file_exists(host):
    """Verify that static page exists"""
    mydist = host.system_info.distribution.capitalize()
    assert (
        host.file(f"{VARS['deb_web_loc']}/index.html").exists
        if mydist == "Debian"
        else host.file(f"{VARS['rh_web_loc']}/index.html").exists
    )


@pytest.mark.parametrize("key", KEYPHRASE)
def test_deploy_static_page__file_contains(host, key):
    """Verify that static page contains keyword"""
    mydist = host.system_info.distribution.capitalize()
    assert (
        host.file(f"{VARS['deb_web_loc']}/index.html").contains(key)
        if mydist == "Debian"
        else host.file(f"{VARS['rh_web_loc']}/index.html").contains(key)
    )
