[tox]
minversion = 3.2.0
envlist=linter,py313

[testenv]
base_python=python3.13
deps =
    -r requirements-dev.txt

[testenv:linter]
commands =
    ruff check test
    ruff format --check --diff test
    mypy -p test
    ansible-lint
skip_install = true
skip_sdist = true

[testenv:fix]
commands =
    ruff format test
    ruff check --fix test
skip_install = true
skip_sdist = true

[testenv:verify]
commands =
    pytest -vvvrxXs --color=yes -W "ignore::UserWarning" {posargs}
