[tox]
minversion = 3.2.0
envlist=linter,py313

[testenv]
base_python=python3.13
deps=.[dev]

[testenv:linter]
deps =
  -r requirements-dev.txt
commands =
    ruff check test
    ruff format --check --diff test
    mypy -p test
    ansible-lint
skip_install = true
skip_sdist = true

[testenv:fix]
deps =
  -r requirements-dev.txt
commands =
    ruff format test
    ruff check --fix test
skip_install = true
skip_sdist = true

